export const ACTIONS = {
  SET_DATA: 'SET_DATA',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_SCENARIO: 'SET_SCENARIO',
  SET_MODE: 'SET_MODE',
  SET_AI_INSIGHT: 'SET_AI_INSIGHT',
  SET_AI_LOADING: 'SET_AI_LOADING',
  SET_AI_ERROR: 'SET_AI_ERROR',
  UPDATE_DATA: 'UPDATE_DATA',
  RESET_DATA: 'RESET_DATA',
} as const;
